### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by kingofwap** [sadiqrazasyed/wallpaperboard-enhanced#1]
how do i update the app with new code ? if you are updating something.

**Comment by sadiqrazasyed** [comment]
As of now since both, "library" as well as the sample "app" template are into one project, you need to do as follows : 

1) Download the entire project
2) Uncompress the zip file & copy "build.gradle" and /app/src/main/res/values/"dashboard_configurations.xml" file from the app folder & paste it on your desktop
2) Replace only the "app" folder inside the uncompressed project folder with your current modified "app" as generally the changes are made towards the library.
3) After replacing the app folder with your own, copy "build.gradle" & "dashboard_configurations.xml" from your desktop (which you had copied from the latest version) & paste them in their respective places - "build.gradle" inside app folder & "dashboard_configurations.xml" in /app/src/main/res/values/.
4) Open Android Studio & import this version.

Note : The changes which you had made inside "dashboard_configurations.xml" will revert back to default, so you have to re-apply the changes again.

Note 2 : I will host library & sample app separately so you don't have to go through such issues again in future.

**Comment by kingofwap** [comment]
thank you

**Comment by kingofwap** [comment]
Is there any chances of bringing Banner ad ?

**Comment by sadiqrazasyed** [comment]
An update will be coming out soon with banner ad support.

Cheers.

**Comment by kingofwap** [comment]
thanks bro waiting
