### ISSUE TITLE
Git issue

### ISSUE THREAD

**Issue by kingofwap** [sadiqrazasyed/wallpaperboard-enhanced#2]
Am getting this error on the new update. may i know how to fix this issue?
thank you

Invalid VCS root mapping
The directory C:\and_work\Amoled is registered as a Git root, but no Git repositories were found there.
Configure

**Comment by sadiqrazasyed** [comment]
It is caused due to the .idea folder within the repository. Inside it are vcs related files which contain a path which is obviously not on your PC. Just ignore it or if you don't wanna see it, then follow this:

1) Click on "configure"
2) It'll open a popup menu, straight to "version control"
3) Choose your project which will show up along with the directory and click on the "minus" button which is located on the side
4) Then just click on "Apply" & then "Ok" button.

This will stop showing you the error.

Screenshot Examples : 

![screen shot 2017-12-13 at 4 30 00 pm](https://user-images.githubusercontent.com/7279710/33936163-979923e0-e024-11e7-8651-ab87f9c29ece.png)

![screen shot 2017-12-13 at 4 35 03 pm](https://user-images.githubusercontent.com/7279710/33936181-aad29aa4-e024-11e7-9784-e3b67b9ff26e.png)

![screen shot 2017-12-13 at 4 35 17 pm](https://user-images.githubusercontent.com/7279710/33936184-afd9e836-e024-11e7-8eca-1b43f3d6dc97.png)

**Comment by kingofwap** [comment]
thanks bro & may i know when banner ad will release ?
